// Tipo de mascota
export const tipoMascotaMap: Record<string, string> = {
    'Gato': '1',
    'Perro': '2',
};

// Género de mascota
export const generoMascotaMap: Record<string, string> = {
    'Hembra': '1',
    'Macho': '2',
};

// Razas de gatos
export const razaGatoMap: Record<string, string> = {
    'Abisinio': '1',
    'Americano de Pelo Corto': '55',
    'Azul Ruso': '73',
    'American Shorthair': '79',
    'American Wirehair': '89',
    'American Curl': '90',
    'Abyssinian': '100',
    'American Bobtail': '107',
    'Arabian Mau': '111',
    'Australian Mist': '118',
    'Bengalí': '5',
    'Bombay': '7',
    'British Shorthair': '11',
    'Bosque de Noruega': '63',
    'Balinés': '66',
    'Birmano': '71',
    'British Longhair': '82',
    'Burmilla': '83',
    'Birman': '86',
    'Burmese': '113',
    'Bristol': '123',
    'Balinese': '124',
    'Bengal': '132',
    'Cornish Rex': '65',
    'Chausie': '72',
    'Chartreux': '93',
    'California Spangled': '99',
    'Cheetoh': '114',
    'Chinese Li Hua': '122',
    'Cymric': '131',
    'Colorpoint Shorthair': '139',
    'Devon Rex': '22',
    'Dragon Li': '91',
    'Don Sphynx': '106',
    'Exótico de Pelo Corto': '59',
    'European Burmese': '94',
    'Egyptian Mau': '95',
    'Exotic Shorthair': '102',
    'Gato Angora Turco': '25',
    'Gato Azul Ruso': '26',
    'Gato Himalayo': '27',
    'Gato Oriental': '28',
    'Gato Siberiano': '29',
    'Gato Somali': '30',
    'Gato Van Turco': '31',
    'Himalayo': '64',
    'Highlander': '75',
    'Himalayan': '85',
    'Havana Brown': '104',
    'Javanés': '58',
    'Javanese': '129',
    'Japanese Bobtail': '135',
    'Khao Manee': '87',
    'Kurilian Bobtail': '133',
    'Korat': '141',
    'Lykoi': '127',
    'LaPerm': '136',
    'Maine Coon': '36',
    'Manx': '38',
    'Mekong Bobtail': '125',
    'Minskin': '130',
    'Napoleon': '137',
    'Norwegian Forest': '142',
    'Oriental de Pelo Corto': '57',
    'Ocicat': '62',
    'Oriental Longhair': '105',
    'Oriental Shorthair': '138',
    'Oriental Bicolor': '140',
    'Persa': '40',
    'Peterbald': '60',
    'Persian': '92',
    'Pixiebob': '115',
    'Ragdoll': '43',
    'Russian Blue': '121',
    'Ragamuffin': '143',
    'Scottish Fold': '46',
    'Siamés': '50',
    'Sphynx': '51',
    'Savannah': '56',
    'Selkirk Rex': '61',
    'Somalí': '69',
    'Siberiano': '70',
    'Siamese': '84',
    'Singapura': '88',
    'Snowshoe': '97',
    'Turkish Angora': '103',
    'Turkish Van': '116',
    'Toyger': '128',
    'Thai': '144',
    'Thai Lilac': '145',
    'Ukrainian Levkoy': '78',
};

// Razas de perros
export const razaPerroMap: Record<string, string> = {
    'Akita Inu': '2',
    'Alaskan Malamute': '3',
    'Affenpinscher': '148',
    'Afghan Hound': '149',
    'Airedale Terrier': '150',
    'Akita': '151',
    'Akita Americano': '152',
    'American Bulldog': '153',
    'American Bully': '154',
    'American Cocker Spaniel': '155',
    'American Eskimo': '156',
    'American Foxhound': '157',
    'American Pit Bull Terrier': '158',
    'American Staffordshire Terrier': '159',
    'American Water Spaniel': '160',
    'Anatolian Shepherd Dog': '161',
    'Australian Cattle Dog': '162',
    'Australian Shepherd': '163',
    'Australian Silky Terrier': '164',
    'Australian Terrier': '165',
    'Beagle': '4',
    'Bichón Frisé': '6',
    'Border Collie': '8',
    'Boston Terrier': '9',
    'Boxer': '10',
    'Bull Terrier': '12',
    'Bulldog Francés': '13',
    'Burmés': '14',
    'Basenji': '166',
    'Basset Hound': '167',
    'Bearded Collie': '168',
    'Beauceron': '169',
    'Bedlington Terrier': '170',
    'Belgian Malinois': '171',
    'Belgian Sheepdog': '172',
    'Belgian Tervuren': '173',
    'Bergamasco': '174',
    'Berger Picard': '175',
    'Bernese Mountain Dog': '176',
    'Bichon Frise': '177',
    'Black and Tan Coonhound': '178',
    'Black Russian Terrier': '179',
    'Bloodhound': '180',
    'Border Terrier': '181',
    'Borzoi': '182',
    'Bouvier des Flandres': '183',
    'Boykin Spaniel': '184',
    'Briard': '185',
    'Brittany': '186',
    'Brussels Griffon': '187',
    'Bulldog': '188',
    'Bullmastiff': '189',
    'Cane Corso': '15',
    'Chihuahua': '16',
    'Cocker Spaniel': '17',
    'Criolla': '18',
    'Criollo': '19',
    'Cairn Terrier': '190',
    'Canaan Dog': '191',
    'Cardigan Welsh Corgi': '192',
    'Cavalier King Charles Spaniel': '193',
    'Chesapeake Bay Retriever': '194',
    'Chinese Crested': '195',
    'Chinese Shar-Pei': '196',
    'Chow Chow': '197',
    'Clumber Spaniel': '198',
    'Cockapoo': '199',
    'Collie': '200',
    'Coonhound': '201',
    'Coton de Tulear': '202',
    'Curly-Coated Retriever': '203',
    'Dachshund (Perro Salchicha)': '20',
    'Dálmata': '21',
    'Doberman': '23',
    'Dachshund': '204',
    'Dalmatian': '205',
    'Dandie Dinmont Terrier': '206',
    'Doberman Pinscher': '207',
    'Dogo Argentino': '208',
    'Dogue de Bordeaux': '209',
    'Dutch Shepherd': '210',
    'English Bulldog': '211',
    'English Cocker Spaniel': '212',
    'English Foxhound': '213',
    'English Setter': '214',
    'English Springer Spaniel': '215',
    'English Toy Spaniel': '216',
    'Entlebucher Mountain Dog': '217',
    'Eskimo Dog': '218',
    'French Bulldog': '223',
    'Golden Retriever': '32',
    'German Pinscher': '224',
    'German Shepherd Dog': '225',
    'German Shorthaired Pointer': '226',
    'German Wirehaired Pointer': '227',
    'Giant Schnauzer': '228',
    'Glen of Imaal Terrier': '229',
    'Gordon Setter': '230',
    'Great Dane': '231',
    'Great Pyrenees': '232',
    'Greater Swiss Mountain Dog': '233',
    'Greyhound': '234',
    'Husky Siberiano': '33',
    'Harrier': '235',
    'Havanese': '236',
    'Ibizan Hound': '237',
    'Icelandic Sheepdog': '238',
    'Irish Setter': '239',
    'Irish Terrier': '240',
    'Irish Water Spaniel': '241',
    'Irish Wolfhound': '242',
    'Italian Greyhound': '243',
    'Jack Russell Terrier': '34',
    'Japanese Chin': '244',
    'Keeshond': '245',
    'Kerry Blue Terrier': '246',
    'King Charles Spaniel': '247',
    'Komondor': '248',
    'Kooikerhondje': '249',
    'Kuvasz': '250',
    'Labrador Retriever': '35',
    'Lagotto Romagnolo': '251',
    'Lakeland Terrier': '252',
    'Lhasa Apso': '253',
    'Lowchen': '254',
    'Maltés': '37',
    'Maltese': '255',
    'Manchester Terrier': '256',
    'Mastiff': '257',
    'Miniature Bull Terrier': '258',
    'Miniature Pinscher': '259',
    'Miniature Schnauzer': '260',
    'Newfoundland': '261',
    'Norfolk Terrier': '262',
    'Norwegian Buhund': '263',
    'Norwegian Elkhound': '264',
    'Norwegian Lundehund': '265',
    'Norwich Terrier': '266',
    'Nova Scotia Duck Tolling Retriever': '267',
    'Old English Sheepdog': '268',
    'Otterhound': '269',
    'Pastor Alemán': '39',
    'Poodle': '41',
    'Pug': '42',
    'Pomerania': '54',
    'Papillon': '270',
    'Pekingese': '271',
    'Pembroke Welsh Corgi': '272',
    'Perro de Agua Español': '273',
    'Perro de Presa Canario': '274',
    'Petit Basset Griffon Vendéen': '275',
    'Pharaoh Hound': '276',
    'Plott': '277',
    'Pointer': '278',
    'Polish Lowland Sheepdog': '279',
    'Pomeranian': '280',
    'Portuguese Water Dog': '281',
    'Presa Mallorquin': '282',
    'Puli': '283',
    'Pumi': '284',
    'Pyrenean Shepherd': '285',
    'Rottweiler': '44',
    'Rat Terrier': '286',
    'Redbone Coonhound': '287',
    'Rhodesian Ridgeback': '288',
    'Samoyedo': '45',
    'Scottish Terrier': '47',
    'Shar Pei': '48',
    'Shih Tzu': '49',
    'Staffordshire Bull Terrier': '52',
    'Saint Bernard': '289',
    'Saluki': '290',
    'Samoyed': '291',
    'Schipperke': '292',
    'Scottish Deerhound': '293',
    'Sealyham Terrier': '294',
    'Shetland Sheepdog': '295',
    'Shiba Inu': '296',
    'Siberian Husky': '297',
    'Silky Terrier': '298',
    'Skye Terrier': '299',
    'Sloughi': '300',
    'Soft-Coated Wheaten Terrier': '301',
    'Spanish Mastiff': '302',
    'Spinone Italiano': '303',
    'Standard Schnauzer': '304',
    'Sussex Spaniel': '305',
    'Swedish Vallhund': '306',
    'Thai Ridgeback': '307',
    'Tibetan Mastiff': '308',
    'Tibetan Spaniel': '309',
    'Tibetan Terrier': '310',
    'Toy Fox Terrier': '311',
    'Treeing Walker Coonhound': '312',
    'Vizsla': '53',
    'Weimaraner': '313',
    'Welsh Springer Spaniel': '314',
    'Welsh Terrier': '315',
    'West Highland White Terrier': '316',
    'Whippet': '317',
    'Wire Fox Terrier': '318',
    'Xoloitzcuintli': '319',
    'Yorkshire Terrier': '320',
};
